import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/Nav/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arlind Pestisha</title>
        <meta name="portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  );
}
