import Head from "next/head";
import Hero from "../components/Hero/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arlind Pestisha</title>
        <meta name="portfolio" content="Generated by create next app" />
      </Head>
      <Hero />
    </div>
  );
}
